### ISSUE TITLE
QXcbConnection: Could not connect to display

### ISSUE THREAD

**Issue by Limoli** [SebastiaanKlippert/go-wkhtmltopdf#17]
As already opened here => [Bug](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2037#issuecomment-62019521), I retrieve this error message trying to generate a PDF from a "working" HTML.
I am not able to adapt that because I am not using wkhtmltopdf as pure command, but obviously using this library.
Is it possible to adapt this with xvfb command?

**Comment by SebastiaanKlippert** [comment]
Not sure I can help with this. I also have no way to test this.

But since my library only sets the arguments to wkhtmltopdf, you could try to call `xvfb wkhtmlptopdf` yourself using [os.Cmd](https://golang.org/pkg/os/exec/#Command) and then pass the arguments from [Args](https://godoc.org/github.com/SebastiaanKlippert/go-wkhtmltopdf#PDFGenerator.Args)
