### ISSUE TITLE
wkhtmltopdf path is missing 

### ISSUE THREAD

**Issue by rbrahul** [SebastiaanKlippert/go-wkhtmltopdf#20]
I have installed wkhtmltopdf successfully.
if I run 

```
$which wkhtmltopdf // /usr/local/bin/wkhtmltopdf
```
And I have also set $WKHTMLTOPDF_PATH variable

Here is my simple code which tries to create pdf. It shows me error `fork/exec : no such file or directory`

```go
const html = `<!doctype html><html><head><title>Hello world!!</title></head><body>Life is awesome</body></html>`
	// Client code
	pdf.SetPath("/usr/local/bin/wkhtmltopdf")
	pdfg := pdf.NewPDFPreparer()
	fmt.Println("PATH IS:", pdf.GetPath())
	// PATH IS: /usr/local/bin/wkhtmltopdf
	pdfg.AddPage(pdf.NewPageReader(strings.NewReader(html)))
	pdfg.Dpi.Set(600)

	err := pdfg.Create()
	if err != nil {
		log.Fatal(err)
	}
```

**Comment by SebastiaanKlippert** [comment]
Hi,

You should use [NewPDFGenerator](https://godoc.org/github.com/SebastiaanKlippert/go-wkhtmltopdf#NewPDFGenerator)

This should return an error immediately when creating it, let me know if that works OK.

The NewPDFPreparer is to prepare a JSON file to be rendered later, although this should work when you have called SetPath, that may be a bug. I will check that later.

**Comment by rbrahul** [comment]
Hi @SebastiaanKlippert ,
I have tried NewPDFGenerator, it worked fine. And thanks for your instant reply. Nice work 👍

**Comment by SebastiaanKlippert** [comment]
Excellent

**Comment by SantoshSah** [comment]
Hello @SebastiaanKlippert , thank you for your work on this wrapper. 

I am getting error `fork/exec /usr/bin/wkhtmltopdf: no such file or directory` in above example after replacing `NewPDFPreparer()` with `NewPDFGenerator()` at the below line
`err := pdfg.Create()`

I am copying executable `wkhtmltopdf` in folder `/usr/bin/` in Dockerfile by below code
`COPY ./lib/wkhtmltopdf /usr/bin/wkhtmltopdf`

I assume that `wkhtmltopdf` is being copied to docker image correctly because `NewPDFGenerator` is not throwing any error immediately. When i do not copy `wkhtmltopdf` to docker image, `NewPDFGenerator` is throwing below error 
`wkhtmltopdf not found` immediately at line 
`pdfg, err := pdf.NewPDFGenerator()`

Am i doing any wrong anywhere?

**Comment by SebastiaanKlippert** [comment]
Hi Santosh, 

It is strange that NewPDFGenerator is not throwing an error, but Create is. That should not happen because the path is stored and should not change.
Without seeing your code I can only guess. Maybe your current working dir is changing somehow in Docker or you are calling SetPath yourself.

First of all make sure that your wkhtmltopdf binary is executable by running `chmod +x` on it before or after copying it to your Dockerfile.

I would guess that `/usr/bin/` is already in PATH, but just to make sure you could try:

- Setting the path by calling `os.Setenv("WKHTMLTOPDF_PATH", "/usr/bin/"))` and make sure you don't use `pdf.SetPath` anywhere in your code
- Or if that does not work, do try to call `pdf.SetPath("/usr/bin/")` before calling `err := pdfg.Create()`

**Comment by SantoshSah** [comment]
Thank you @SebastiaanKlippert for your reply. 

I am trying with code from [simplesample_test.go](https://github.com/SebastiaanKlippert/go-wkhtmltopdf/blob/master/simplesample_test.go). Below is screenshot of code:
<img width="597" alt="pdf-code-sample" src="https://user-images.githubusercontent.com/2204972/105611077-55954900-5ddb-11eb-862b-f699a088a9b6.png">


I tried all options you suggested but error remains same. When i do not copy `wkhtmltopdf` to docker build, `NewPDFGenerator()` throws error otherwise `pdfg.Create()` throws error mentioned above. Below is screenshot of error:
<img width="1089" alt="Error-Creating-File" src="https://user-images.githubusercontent.com/2204972/105611150-ba50a380-5ddb-11eb-8ab8-cde431c9e2e9.png">


I also tried to copy `wkhtmltopdf` to different folders like root of working directory `/`, `/usr/bin/`, `/usr/local/bin/` and verified if `wkhtmltopdf` has been copied to these folders and have appropriate permission to execute it but no avail. Below are screenshots of list of files in `/usr/bin/` and stat of `wkhtmltopdf`:
<img width="911" alt="usr-bin-content" src="https://user-images.githubusercontent.com/2204972/105611225-17e4f000-5ddc-11eb-9078-51a1c1fe4639.png">

<img width="663" alt="wkhtmltopdf-stat" src="https://user-images.githubusercontent.com/2204972/105611237-2501df00-5ddc-11eb-9180-e92a488b1081.png">


I also tried to copy with command `COPY ./lib/wkhtmltopdf /usr/bin/` so that original file flags do not get changed, but no avail. 

When you get some free time, please try to run simplesample_test.go code on Kubernetes using multi-stag build with Dockerfile. Below is content of Dockerfile with some sensitive informations removed.

```
FROM golang:alpine AS build_base

#Set working directory for project
WORKDIR /src

# Install some dependencies needed to build the project
#RUN apk add bash ca-certificates git gcc g++ libc-dev
RUN apk add --no-cache --update \
        git ca-certificates 

# Add go.mod and go.sum first to maximize caching
# We want to populate the module cache based on the go.{mod,sum} files. 
COPY go.mod .
COPY go.sum .

#This is the ‘magic’ step that will download all the dependencies that are specified in the go.mod and go.sum file.
RUN go mod download

# This image builds the server
FROM build_base AS server_builder

# Here we copy the rest of the source code
COPY . .

# And compile the project
RUN GOOS=linux GOARCH=amd64 go install ./cmd/app_server

#In this last stage, we start from a fresh Alpine image, to reduce the image size and not ship the Go compiler in our production artifacts.
FROM alpine AS appservice

# We add the certificates to be able to verify remote instances
RUN apk add ca-certificates

# Finally we copy the statically compiled Go binary.
COPY --from=server_builder /go/bin/app_server /bin/app_server

# Copy env & other files to final image so that env variables can be used by executable
COPY dev.env .
COPY ./gen/http/openapi.yaml ./gen/http/openapi.yaml

COPY ./lib/wkhtmltopdf /usr/bin/
RUN chmod +x /usr/bin/wkhtmltopdf

CMD env `cat dev.env | grep -v '^\s*#'` /bin/app_server

```

Please let me know if you need any other information from me to trace and fix the problem.

**Comment by SebastiaanKlippert** [comment]
This looks like it is not a problem in my wrapper then I would say. I guess wkhtmltopdf is not properly installed, than also explains why NewPDFGenerator is finding the binary fine, but there is an error when you run it.

Can you just try without any Go code to just bash into your container and run wkhtmltopdf  directly?
Something like `wkhtmltopdf http://www.google.com google.pdf`

There are some dependencies needed to run wkhtmltopdf properly and they are not included in Alpine by default, you can take a look at https://github.com/Surnet/docker-wkhtmltopdf or just use https://hub.docker.com/r/surnet/alpine-wkhtmltopdf as your base image and copy your go binary into there instead of the other way round.

**Comment by SantoshSah** [comment]
Hello @SebastiaanKlippert ,

Thank you for your suggestion. It seems that some libraries were missing. Copying `wkhtmltopdf` from `surnet/alpine-wkhtmltopdf` to final image worked.

**Comment by anooprav** [comment]
Hello @SantoshSah 
Do you mind sharing the Dockerfile with me? It's working for me with a package manager, but it ended up making the docker image bloated.
Copying the binaries to base alpine image isn't working for me.

**Comment by SantoshSah** [comment]
Hello @anooprav ,

Below is working Dockerfile for me with some information changed/removed but everything is there that help running wkhtmltopdf. Please note that docker image size will be increased after copying `surnet/alpine-wkhtmltopdf`. 

```
FROM golang:alpine AS build_base

#Set working directory for project
WORKDIR /src

# Install some dependencies needed to build the project
#RUN apk add bash ca-certificates git gcc g++ libc-dev
RUN apk add --no-cache --update \
  git ca-certificates

# Force fetching modules over SSH using Github Access Token(https://github.com/settings/tokens)
# Ref: https://medium.com/paperchain/fetching-private-github-repos-from-a-docker-container-273f25ec5a74
ARG GITHUB_ACCESS_TOKEN
RUN git config --system url."https://$GITHUB_ACCESS_TOKEN:@github.com/my-project/".insteadOf "https://github.com/my-project/"

# Add go.mod and go.sum first to maximize caching
# We want to populate the module cache based on the go.{mod,sum} files. 
COPY go.mod .
COPY go.sum .

#This is the ‘magic’ step that will download all the dependencies that are specified in the go.mod and go.sum file.
ENV GOPRIVATE="github.com/my-project"
# RUN go mod tidy
RUN go mod download

# This image builds the server
FROM build_base AS server_builder

# Here we copy the rest of the source code
COPY . .

# And compile the project
RUN GOOS=linux GOARCH=amd64 go install ./cmd/project_server

FROM surnet/alpine-wkhtmltopdf:3.12-0.12.6-small as wkhtmltopdf
#In this last stage, we start from a fresh Alpine image, to reduce the image size and not ship the Go compiler in our production artifacts.
FROM alpine AS projectservice

# Install dependencies for wkhtmltopdf
RUN apk add --no-cache libstdc++ libx11 libxrender libxext libssl1.1 fontconfig freetype ttf-dejavu ttf-droid ttf-freefont ttf-liberation ttf-ubuntu-font-family && apk add --no-cache --virtual .build-deps msttcorefonts-installer && update-ms-fonts && fc-cache -f && rm -rf /tmp/* && apk del .build-deps

# We add the certificates to be able to verify remote instances
RUN apk add ca-certificates

# Finally we copy the statically compiled Go binary.
COPY --from=server_builder /go/bin/project_server /bin/project_server

# Copy wkhtmltopdf files from docker-wkhtmltopdf final image
COPY --from=wkhtmltopdf /bin/wkhtmltopdf /bin/wkhtmltopdf

# Copy env file to final image so that env variables can be used by executable
COPY dev.env .
COPY ./gen/http/openapi.yaml ./gen/http/openapi.yaml
COPY ./templates ./templates

# pass enviornmental variables to command(ref:https://github.com/moby/moby/issues/28617#issuecomment-313706632)
CMD env `cat dev.env | grep -v '^\s*#'` /bin/project_server
#ENTRYPOINT ["/bin/project"]

```

Please look at below three lines in Dockerfile for wkhtmltopdf to work. Rest of code may not be irrelevant to you but shared assuming it may help you or others.

`FROM surnet/alpine-wkhtmltopdf:3.12-0.12.6-small as wkhtmltopdf`

```
# Install dependencies for wkhtmltopdf
RUN apk add --no-cache libstdc++ libx11 libxrender libxext libssl1.1 fontconfig freetype ttf-dejavu ttf-droid ttf-freefont ttf-liberation ttf-ubuntu-font-family && apk add --no-cache --virtual .build-deps msttcorefonts-installer && update-ms-fonts && fc-cache -f && rm -rf /tmp/* && apk del .build-deps

```

and

```
# Copy wkhtmltopdf files from docker-wkhtmltopdf final image
COPY --from=wkhtmltopdf /bin/wkhtmltopdf /bin/wkhtmltopdf
```
