### ISSUE TITLE
Intermittent blank output

### ISSUE THREAD

**Issue by EwanValentine** [SebastiaanKlippert/go-wkhtmltopdf#25]
**wkhtmltopdf version(s) affected**: 0.12.5

**OS information**
Both Mac OSX and Alpine Docker.

**Description**
I have a large (ish), html template and some Javascript. But I can also recreate this problem using plain-text. The problem I'm seeing is, on the first attempt at converting a html string into a PDF, it works as expected. However, on the second or third time, instead of generating my 9 page PDF. It generates 3 or 4 completely blank pages. 

When I output the html in the above scenario, it's correct. It seems to be during the PDF generation process. I first observed this when running in an Alpine Linux container, however I am now seeing this on my laptop also. 

**How to reproduce**
1. Set-up a go file using `go-wkhtmltopdf`.
2. Use the function below:
```go
func generatePDF(pdfg *pdf.PDFGenerator, html []byte) ([]byte, error) {
	pdfg.PageSize.Set(pdf.PageSizeA4)
	pdfg.MarginTop.Set(0)
	pdfg.MarginLeft.Set(0)
	pdfg.MarginRight.Set(0)
	pdfg.Dpi.Set(300)
	page := pdf.NewPageReader(bytes.NewReader(html))
	page.JavascriptDelay.Set(500)
	pdfg.AddPage(page)
	if err := pdfg.Create(); err != nil {
		return nil, err
	}
	return pdfg.Bytes(), nil
}
```

Use the following Docker image to replicate the exact environment: 
```dockerfile
# build stage
FROM golang:alpine AS build-env

RUN apk add --no-cache gcc git cmake musl-dev
RUN mkdir -p /usr/go/src/github.com/EwanValentine/report-service
RUN go get -u golang.org/x/vgo

WORKDIR /usr/go/src/github.com/EwanValentine/report-service

ADD . .
ADD templates templates

RUN vgo install && vgo build -o svc

# final stage
FROM surnet/alpine-wkhtmltopdf:3.7-0.12.5-full

COPY --from=build-env /usr/go/src/github.com/EwanValentine/report-service/ /app/

WORKDIR /app

ENTRYPOINT ./svc

```

I can re-produce this using just plain-text, and without any html.

**Expected behavior**

I'd expect content to render into the document.

**Comment by SebastiaanKlippert** [comment]
Thanks for the detailed error report, the first thing that comes to mind is
that you are re-use the same PDF generator object, which might be the
problem.
Can you try to use SetPages instead of AddPage?
https://godoc.org/github.com/SebastiaanKlippert/go-wkhtmltopdf#PDFGenerator.SetPages

If that does not work I will look into it later this week.

Op 24 okt. 2018 01:03 schreef "Ewan Valentine" <notifications@github.com>:

*wkhtmltopdf version(s) affected*: 0.12.5

*OS information*
Both Mac OSX and Alpine Docker.

*Description*
I have a large (ish), html template and some Javascript. But I can also
recreate this problem using plain-text. The problem I'm seeing is, on the
first attempt at converting a html string into a PDF, it works as expected.
However, on the second or third time, instead of generating my 9 page PDF.
It generates 3 or 4 completely blank pages.

When I output the html in the above scenario, it's correct. It seems to be
during the PDF generation process. I first observed this when running in an
Alpine Linux container, however I am now seeing this on my laptop also.

*How to reproduce*

   1. Set-up a go file using go-wkhtmltopdf.
   2. Use the function below:

func generatePDF(pdfg *pdf.PDFGenerator, html []byte) ([]byte, error) {
	pdfg.PageSize.Set(pdf.PageSizeA4)
	pdfg.MarginTop.Set(0)
	pdfg.MarginLeft.Set(0)
	pdfg.MarginRight.Set(0)
	pdfg.Dpi.Set(300)
	page := pdf.NewPageReader(bytes.NewReader(html))
	page.JavascriptDelay.Set(500)
	pdfg.AddPage(page)
	if err := pdfg.Create(); err != nil {
		return nil, err
	}
	return pdfg.Bytes(), nil
}

Use the following Docker image to replicate the exact environment:

# build stageFROM golang:alpine AS build-env
RUN apk add --no-cache gcc git cmake musl-devRUN mkdir -p
/usr/go/src/github.com/EwanValentine/report-serviceRUN go get -u
golang.org/x/vgo
WORKDIR /usr/go/src/github.com/EwanValentine/report-service
ADD . .ADD templates templates
RUN vgo install && vgo build -o svc
# final stageFROM surnet/alpine-wkhtmltopdf:3.7-0.12.5-full
COPY --from=build-env /usr/go/src/github.com/EwanValentine/report-service/ /app/
WORKDIR /app
ENTRYPOINT ./svc

I can re-produce this using just plain-text, and without any html.

*Expected behavior*

I'd expect content to render into the document.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/SebastiaanKlippert/go-wkhtmltopdf/issues/25>, or mute
the thread

**Comment by EwanValentine** [comment]
Hey! Just trying this out now. Because I'm using a Go template, which returns bytes etc. I have to use the `PageReader` struct, which doesn't seem to play nicely with `SetPages`. 

I tried using: `var pages []*wkhtmlpfg.PageReader` but it's not compatible. Is there a way to convert page readers to final pages? 

Cheers!

**Comment by SebastiaanKlippert** [comment]
Hi,

I see, the page interface is not exported so can't do that, sorry.
To be honest, I would just call `NewPDFGenerator()` to create a new object for every PDF you create, that is the intended use of this package. If you ever want to do anything with concurrency you also can't reuse the PDFGenerator struct.
As a workaround you could try calling `pdfg.SetPages(nil)` before calling `pdfg.AddPage(page)`.

I am not even sure if this solves your issue, but it may come from the fact that you are reusing the PDF generator.

If resetting pages does not help and if creating a new PDFGenerator object for each PDF also doesn't work, I will look into it further, but that will have to wait a few days until I can make time.

**Comment by EwanValentine** [comment]
Hey, 

That hotfix actually worked perfectly! I'm aware it's probably not the best approach though, so I'll look into the other things you mentioned. By 'reusing the PDF generator', do you mean because I'm instantiating a single instance in my `func main() {}` then passing it from a loop into a function by reference?

Should I call:
```go
pdfg, err := pdf.NewPDFGenerator()
```

In the top of my `generatePDF()` function instead in that case?

**Comment by SebastiaanKlippert** [comment]
Good to hear that it worked. And yes, that is exactly what is meant. Just
call NewPDFGenerator in your function, the overhead is minimal as the
package already caches the location of wkhtmltopdf, so it does not need to
look that up every time.

**Comment by EwanValentine** [comment]
Oh great! I'll do that instead, thanks for your help and hard-work :)
