### ISSUE TITLE
Network Error: ContentNotFoundError

### ISSUE THREAD

**Issue by ytanne** [SebastiaanKlippert/go-wkhtmltopdf#43]
I was trying to generate a PDF file from the HTML. However, when I tried to compile code, it exit with the following error:

> 2020/02/18 12:50:13 libpng warning: iCCP: known incorrect sRGB profile
> libpng warning: iCCP: known incorrect sRGB profile
> Loading page (1/2)
> Warning: Failed to load file:///tmp/styles.css (ignore)           
> Printing pages (2/2)                                               
> Done                                                           
> Exit with code 1 due to network error: ContentNotFoundError
> exit status 1

I have included my CSS file in the header in the same directory where the HTML file is.
> <link rel="stylesheet" href="styles.css" >
The code stops at Create() function of PDFGenerator structure.
Have anyone faced this issue? How can I specify my stylesheet?

**Comment by SebastiaanKlippert** [comment]
Without seeing your Go code, I think, this issue is known, I investigated last week here https://github.com/SebastiaanKlippert/go-wkhtmltopdf/issues/28#issuecomment-585308645

But unfortunatley I don't have a solution, seems to be an issue in wkhtmltopdf itself: https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3014

Are you use a `NewPageReader` in your Go code? 
If you have the html on disk, the easiest workaround is to rewrite to `NewPage`.

```go
page  := wkhtml.NewPage("test.html")
```

That is then using the same behaviour as when calling wkhtml directly from command line.

Another option (and I think it is the safest option) is to not depend on relative paths in your HTML and put in an absolute file link to your CSS file.

**Comment by ytanne** [comment]
Thanks, you were right. The problem was in wkhtmltopdf.
