### ISSUE TITLE
why not use  $GOPATH/pkg or $GOPATH/bin

### ISSUE THREAD

**Issue by ORESoftware** [SebastiaanKlippert/go-wkhtmltopdf#46]
As for looking up the binary executable path:

```
go-wkhtmltopdf finds the path to wkhtmltopdf by

first looking in the current dir
looking in the PATH and PATHEXT environment dirs
using the WKHTMLTOPDF_PATH environment dir
```

why not also look in  $GOPATH/bin ,  $GOROOT/bin ?

when this lib is included as a dependency using go modules, can it automatically install itself as a binary?

**Comment by SebastiaanKlippert** [comment]
> why not also look in $GOPATH/bin , $GOROOT/bin ?

Because wkhtmltopdf is not a Go project, so it would not be installed in your  $GOPATH/bin and also not in $GOROOT/bin because that is for Go runtime binaries. 
But because Go setup recommends that you include both in your PATH, (or does this for you under Windows) it would still work if you were to install wkhtmltopdf there.

> when this lib is included as a dependency using go modules, can it automatically install itself as a binary?

It can, but it cannot install wkhtmltopdf for your OS.
