### ISSUE TITLE
CSS document not found 

### ISSUE THREAD

**Issue by Almodovar** [SebastiaanKlippert/go-wkhtmltopdf#5]
Hi Sebastiaan, 

I noticed you define many class in the sample html5 file but did not find any css file. I am wondering how the html can be styled to fit printing format.  

Best
Kun

**Comment by SebastiaanKlippert** [comment]
Hi,

The html5 in the samples is not something I made, it is just to test if my options are called correctly, so this in no way something to look at when trying to render pages correctly.

I am not really a CSS specialist, we have front-end designers who create our layouts, but I know they use the CSS print-media type.
It is similar to what is described in this tutorial: http://www.tutorialspoint.com/css/css_paged_media.htm

And in some lay-outs, which we display both on screen and print we set a page style using sizes in millimeters (or inches). For A4 we use
```css
.page {
    width: 210mm;
    height: 297mm;
}
```

In wkhtmltopdf we then use the -print-media-type flag, set the pagesize and set the margins to 0 because we control our margins in CSS, they are variables in our print settings and inserted in the CSS objects using the go html template engine. But you could also choose to set them in the Go code using the margin flags below.

Our wkhtmltopdf code is basically just this:
```go
//object.Body is the HTML file we download or read earlier.
page := wkhtmltopdf.NewPageReader(object.Body)

page.PrintMediaType.Set(true)

pdfGen.AddPage(page)

pdfGen.Dpi.Set(600) 
pdfGen.PageSize.Set(wkhtmltopdf.PageSizeA4)
pdfGen.MarginLeft.Set(0)
pdfGen.MarginBottom.Set(0)
pdfGen.MarginRight.Set(0)
pdfGen.MarginTop.Set(0)

err := pdfGen.Create()
//etc...
```

The rest is all done by settings the page sizes in CSS print media.
Just keep in mind that rendering uses webkit, so any CSS that is supported there should work just fine.

Hope this helps,

Sebastiaan
