### ISSUE TITLE
io.Reader multi-page problem

### ISSUE THREAD

**Issue by stanislavdev3** [SebastiaanKlippert/go-wkhtmltopdf#74]
Hello!
I faced problems when I try to create PDFs from a few readers, `wkhtmltopdf` generate only one page with content from the first reader (the second reader is ignored). Simple example:

```
...
page := wkhtmltopdf.NewPageReader(firstIOReader[0])
pdfGen.AddPage(page)

page2 := wkhtmltopdf.NewPageReader(secondIOReader)
pdfGen.AddPage(page2)

pdfGen.Create()
...
```

I think the problem is in `wkgtmltopdf.go:322` this brake ignore other readers except first. Could you please fix this problem if it possible (if it is not a limitation of the wkhtmltopdf application) 
I found only one way, that creates temp files and works via `wkhtmltopdf.NewPage()`, but It's quite dirty (and I don't want to torture my HDD :) )

**Comment by SebastiaanKlippert** [comment]
This is technically not possible, in the docs it also mentions you can only use one PageReader (https://pkg.go.dev/github.com/SebastiaanKlippert/go-wkhtmltopdf?utm_source=godoc#PageReader).

The reason is that it is using stdin to feed the document as argument to wkhtmltopdf, so that can be only one input page on each invocation.

The best solution would be to create one input document (HTML document) that contains all the pages.
See https://github.com/SebastiaanKlippert/go-wkhtmltopdf/issues/54

**Comment by stanislavdev3** [comment]
Okay, I got it. Anyway thank you so much
